#! /usr/bin/env python

def get_array_ids(prediction_index,spectrum_index):
    return {
            'X2'           :0,
            "m0"           : 1 ,
            "m12"          : 2 ,
            "A0"           : 3 ,
            "tanb"         : 4 ,
            "mh2"          : 6 ,
            "mhd2"         : 6 ,
            "mhu2"         : 7 ,
            'msq12'        :1, 
            'msq3'         :2, 
            'msl'          :3, 
            'A'            :5, 
            'M1'           :6,
            'in_mu'        :7,
            'in_ma'        :8,
            'M2'           :9,
            'M3'           :10,
            "mtop"         : prediction_index-4, 
            "MZ"           : prediction_index-3, 
            "GZ_in"        : prediction_index-2, 
            "DAlpha_had"   : prediction_index-1, 
            # predictions
            "R(b->sg)"     : prediction_index,  
            "R(D_ms)"      : prediction_index+1, 
            "bsmm"         : prediction_index+2, 
            "R(B->taunu)"  : prediction_index+3, 
            "R(B->Xsll)"   : prediction_index+4, 
            "R(K->lnu)"    : prediction_index+5, 
            "Delta(g-2)"   : prediction_index+6, 
            "MW"           : prediction_index+7, 
            "sintheta_eff" : prediction_index+8, 
            "Gamma_Z"      : prediction_index+9, 
            "Rl"           : prediction_index+10,
            "Rb"           : prediction_index+11,
            "Rc"           : prediction_index+12,
            "Afb(b)"       : prediction_index+13,
            "Afb(c)"       : prediction_index+14,
            "Ab16"         : prediction_index+15,
            "Ac17"         : prediction_index+16,
            "Al(SLD)"      : prediction_index+17,
            "mh"           : prediction_index+18,
            "Oh^2"         : prediction_index+19,
            "Al(P_tau)"    : prediction_index+20,
            "Al_fb"        : prediction_index+21,
            "sigma_had^0"  : prediction_index+22,
            "R(Delta_md)"  : prediction_index+23,
            "R(Delta_mk)"  : prediction_index+24,
            "R(Kp->pinn)"  : prediction_index+25,
            "BR(Bd->ll)"   : prediction_index+26,
            "R(Dms)/R(Dmd)": prediction_index+27,
            "D_0(K*g)"     : prediction_index+28,
            "BR(b->sg)"    : prediction_index+29,
            "mu"           : prediction_index+32,
            "sigma_pp^SI"  : prediction_index+33,
            "mA0^2"        : prediction_index+35,
            #FIXME: FIll in these numbers
#            "KOsigma_pp^SI"  : ,  
#            "KOsigma_pp^SI_cen50"  : , 
#            "KOsigma_pp^SI_unc50_14"  :,
#            "KOsigma_pp^SI_unc50_7"   : ,
            # Spectrum
            "chi1"         : spectrum_index+0,  
            "chi2"         : spectrum_index+1,  
            "neu1"         : spectrum_index+2,  
            "neu2"         : spectrum_index+3,  
            "neu3"         : spectrum_index+4,  
            "neu4"         : spectrum_index+5,  
            "sel_r"        : spectrum_index+6,  
            "sel_l"        : spectrum_index+7,  
            "snu_e"        : spectrum_index+8,  
            "smu_r"        : spectrum_index+9,  
            "smu_l"        : spectrum_index+10, 
            "snu_mu"       : spectrum_index+11, 
            "stau1"       : spectrum_index+12, 
            "stau2"       : spectrum_index+13, 
            "snu_tau"      : spectrum_index+14, 
            "squark_r"     : spectrum_index+15, 
            "squark_l"     : spectrum_index+16, 
            "stop1"        : spectrum_index+17, 
            "stop2"        : spectrum_index+18, 
            "sbottom1"     : spectrum_index+19, 
            "sbottom2"     : spectrum_index+20, 
            "gluino"       : spectrum_index+21, 
            "mh0"          : spectrum_index+22, 
            "mH0"          : spectrum_index+23, 
            "MA"          : spectrum_index+24, 
            "mH+-"         : spectrum_index+25, 
            "ssmh"        : spectrum_index+30, 
            "ssmH0"        : spectrum_index+31, 
            "ssMA"        : spectrum_index+32, 
            "ssmH+-"       : spectrum_index+33, 
            }
