def get():
    return{
            'A': {
                'binning': {
                    'high': 5000.0,
                    'low': -5000.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'A'},
            'A0': {
                'binning': {
                    'high': 5000.0,
                    'low': -5000.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'A0'
                },
            'A0_over_m0': {
                'binning': {
                    'high': 5.0,
                    'low': -5.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'A0_over_m0'
                },
            'BsmmRatio': {
                'binning': {
                    'high': 3.0,
                    'low': 0.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'BsmmRatio'
                },
            'C9': {'binning': {'high': 0.05,
                               'low': -0.05,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'C9'},
            'M1': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'M1'},
            'M2': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'M2'},
            'M3': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'M3'},
            'MA': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'MA'},
            'chi2': {'binning': {'high': 300.0,
                                 'low': 30.0,
                                 'nbins': 500,
                                 'type': 'linear'},
                     'value': 'chi2'},
            'chi2_g-2': {'value': 'g-2'},
            'chi2_jad': {'value': 'universal_limits'},
            'chi2_m3g_only': {'value': 'm3g_universal_limits'},
            'chi2_mg_only': {'value': 'mg_universal_limits'},
            'chi2_mh': {'value': 'Mh125'},
            'chi2_oh2': {'value': 'Oh2'},
            'in_ma': {'binning': {'high': 4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'in_ma'},
            'in_mu': {'binning': {'high': 5000.0,
                                  'low': -5000.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'in_mu'},
            'logmneu1': {'binning': {'high': 1000.0,
                                     'low': 10.0,
                                     'nbins': 100,
                                     'type': 'log'},
                         'value': 'mneu1'},
            'logssicm2': {'binning': {'high': 1e-40,
                                      'low': 1e-48,
                                      'nbins': 100,
                                      'type': 'log'},
                          'value': 'ssicm2'},
            'logssikocm2': {'binning': {'high': 1e-40,
                                        'low': 1e-48,
                                        'nbins': 100,
                                        'type': 'log'},
                            'value': 'ssikocm2'},
            'm0': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'm0'},
            'm12': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'm12'},
            'm12g': {'binning': {'high': 4000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'm12g'},
            'm3g': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'm3g'},
            'mchar1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mchar1'},
            'mg': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mg'},
            'mh': {'binning': {'high': 130.0,
                               'low': 105.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mh'},
            'mh2': {'binning': {'high': 12000000.0,
                                'low': -12000000.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'mh2'},
            'mh2_m0^2_Ratio': {'binning': {'high': 10.0,
                                           'low': -10.0,
                                           'nbins': 100,
                                           'type': 'linear'},
                               'value': 'mh2_m0^2_Ratio'},
            'mh_over_m0': {'binning': {'high': 10.0,
                                       'low': -10.0,
                                       'nbins': 100,
                                       'type': 'linear'},
                           'value': 'mh_over_m0'},
            'mneu1': {'binning': {'high': 4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'mneu1'},
            'mneu1_900': {'binning': {'high': 900.0,
                                      'low': 0.0,
                                      'nbins': 100,
                                      'type': 'linear'},
                          'value': 'mneu1_900'},
            'msbot1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'msbot1'},
            'msbot2': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'msbot2'},
            'msl': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'msl'},
            'msq12': {'binning': {'high': 4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'msq12'},
            'msq3': {'binning': {'high': 4000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'msq3'},
            'msqr': {'binning': {'high': 6000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'msqr'},
            'mstau1': {'binning': {'high': 6000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstau1'},
            'mstop1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstop1'},
            'mstop2': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstop2'},
            'mstop2-mstop1': {'binning': {'high': 1000.0,
                                          'low': 0.0,
                                          'nbins': 100,
                                          'type': 'linear'},
                              'value': 'mstop2-mstop1'},
            'mu': {'binning': {'high': 5000.0,
                               'low': -5000.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mu'},
            'oh2': {'binning': {'high': 0.3, 'low': 0.0, 'nbins': 100, 'type': 'linear'},
                    'value': 'oh2'},
            'ssmh': {'binning': {'high': 130.0,
                                 'low': 105.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'ssmh'},
            'tanb': {'binning': {'high': 60.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'tanb'}}
