def get():
    axes.update(chi2_axes)
    return axes
axes={
            'pmssm-mc9-chi2':{
                'binning':{
                    'low':24,
                    'high':35,
                    'nbins':10000,
                    'type':'linear',
                    },
                'value':'mc9_no_lhc',
                },
            'cmssm-mc9-chi2':{
                'binning':{
                    'low':30,
                    'high':45,
                    'nbins':2000,
                    'type':'linear',
                    },
                'value':'mc9',
                },
            'mtop': {
                'binning': {
                    'high': 175.2,
                    'low': 171.2,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'mtop'},
            'A': {
                'binning': {
                    'high': 5000.0,
                    'low': -5000.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'A'},
            'A0': {
                'binning': {
                    'high': 5000.0,
                    'low': -5000.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'A0'
                },
            'A0_over_m0': {
                'binning': {
                    'high': 5.0,
                    'low': -5.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'A0_over_m0'
                },
            'BsmmRatio': {
                'binning': {
                    'high': 3.0,
                    'low': 0.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'value': 'BsmmRatio'
                },
            'C9': {'binning': {'high': 0.05,
                               'low': -0.05,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'C9'},
            'M1': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'M1'},
            'M2': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'M2'},
            'M3': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'M3'},
            'MA': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'MA'},
            'chi2': {'binning': {'high': 300.0,
                                 'low': 30.0,
                                 'nbins': 500,
                                 'type': 'linear'},
                     'value': 'chi2'},
            'chi2_g-2': {'value': 'g-2'},
            'chi2_jad': {'value': 'universal_limits'},
            'chi2_m3g_only': {'value': 'm3g_universal_limits'},
            'chi2_mg_only': {'value': 'mg_universal_limits'},
            'chi2_mh': {'value': 'Mh125'},
            'chi2Oh2': {
                    'value': 'chi2Oh2',
                    },
            'in_ma': {
                    'binning': {
                        'high': 4000.0,
                        'low': 0.0,
                        'nbins': 100,
                        'type': 'linear'
                        },
                    'value': 'in_ma'},
            'in_mu': {'binning': {'high': 5000.0,
                                  'low': -5000.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'in_mu'},
            'logmneu1': {'binning': {'high': 4000.0,
                                     'low': 10.0,
                                     'nbins': 100,
                                     'type': 'log'},
                         'value': 'mneu1'},
            'logssicm2': {'binning': {'high': 1e-40,
                                      'low': 1e-48,
                                      'nbins': 100,
                                      'type': 'log'},
                          'value': 'ssicm2'},
            'logssikocm2': {'binning': {'high': 1e-40,
                                        'low': 1e-48,
                                        'nbins': 100,
                                        'type': 'log'},
                            'value': 'ssikocm2'},
            'Dssicm2': {
                    'value': 'Dssikocm2'
                    },
            'Dssi': {
                    'value': 'Dssi'
                    },
            'm0': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'm0'},
            'mstau1-mneu1': {'binning': {'high': 30.0,
                               'low': -5.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mstau1-mneu1'},
            'mchar1-mneu1': {'binning': {'high': 30.0,
                               'low': -5.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mchar1-mneu1'},
            'MA-2mneu1': {'binning': {'high': 30.0,
                               'low': -5.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'MA-2mneu1'},
            'nuhm1m0': {'binning': {'high': 4500.0,
                               'low': -500.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'm0'},
            'm0_6K': {'binning': {'high': 6000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'm0'},
            'm0_7K': {'binning': {'high': 7000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'm0'},
            'm12': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'm12'},
            'm12g': {'binning': {'high': 4000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'm12g'},
            'm3g': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'm3g'},
            'mchar1': {'binning': {'high':4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mchar1'},
            'mg': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mg'},
            'mg_6K': {'binning': {'high': 6000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mg'},
            'mg_5K': {'binning': {'high': 5000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mg'},
            'mh': {'binning': {'high': 130.0,
                               'low': 105.0,
                               'nbins': 100,    
                               'type': 'linear'},
                   'value': 'mh'},
            'Dmh': {'binning': {'high': 40.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'Dmh'},
            'fh-ss': {'binning': {'high': 40,
                               'low': -40,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'fh-ss'},
            'mh2': {'binning': {'high': 46000000.0,
                                'low': -46000000.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'mh2'},
            'mh2_m0^2_Ratio': {'binning': {'high': 10.0,
                                           'low': -10.0,
                                           'nbins': 100,
                                           'type': 'linear'},
                               'value': 'mh2_m0^2_Ratio'},
            'mh_over_m0': {'binning': {'high': 10.0,
                                       'low': -10.0,
                                       'nbins': 100,
                                       'type': 'linear'},
                           'value': 'mh_over_m0'},
            'mneu1': {'binning': {'high':4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'mneu1'},
            'mneu1_900': {'binning': {'high': 900.0,
                                      'low': 0.0,
                                      'nbins': 100,
                                      'type': 'linear'},
                          'value': 'mneu1_900'},
            'msbot1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'msbot1'},
            'msbot2': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'msbot2'},
            'msl': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'value': 'msl'},
            'msq12': {'binning': {'high': 4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'msq12'},
            'msq3': {'binning': {'high': 4000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'msq3'},
            'msqr': {'binning': {'high': 6000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'msqr'},
            'mstau1': {'binning': {'high':4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstau1'},
            'mstau1_6K': {'binning': {'high': 6000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstau1'},
            'mstau1_5K': {'binning': {'high': 5000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstau1'},
            'mstop1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstop1'},
            'mstop1_5K': {'binning': {'high': 5000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstop1'},
            'mstop1_6K': {'binning': {'high': 6000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstop1'},
            'mstop2': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mstop2'},
            'mstop2-mstop1': {'binning': {'high': 1000.0,
                                          'low': 0.0,
                                          'nbins': 100,
                                          'type': 'linear'},
                              'value': 'mstop2-mstop1'},
            'mu': {'binning': {'high': 3000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mu'},
            'oh2': {
                    'binning': {
                        'low': 0.0, 
                        'high': 0.3, 
                        'nbins': 100, 
                        'type': 'linear',
                        },
                    'value': 'oh2'
                    },
            'ssmh': {'binning': {'high': 130.0,
                                 'low': 105.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'ssmh'},
            'tanb': {'binning': {'high': 60.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'tanb'},
            'tanb40': {'binning': {'high': 40.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'value': 'tanb'},
            'Delta_alpha_had':{
                    'value':'Delta_alpha_had',
                   },
            'mz':{
                    'value':'mz',
                    },
            'mt':{
                    'value':'mtop',
                    },
            #FIXME: need more elegant way of including this.
            }
            
chi2_axes={name:{'value':'chi2-{}'.format(name)} for name in [ 'Al(SLD)', 'Ab', 'Ac', 'mc9_Oh2', 'mc9_Mh',   
            'Gamma_Z', 'GZ_in', 'R(B->Xsll)', 'Al(P_tau)', 'MZ', 'mc9_R_DMBs', 'MW', 'Afb_l', 
            'xenon100_SpiN_unc', 'xenon100','mc9_DAlpha_had', 'mc9_epsilon_K',  'sigma_had^0', 'Afb(c)', 
            'atlas20_m0_m12', 'Afb(b)',  'mc9_R_B->Xsg', 'mc9_R_DMBs_DMBd', 'mc9_R_B->taunu', 
            'Rc', 'Rb',  'Rl', 'R_Bsmm_mc9', 'sintheta_eff', 'mc9_Mt', 'R(K->lnu)', 'R(Kp->pinn)', 'gminus2mu', 'MATANB' ,
            'LEP-chargino', 'LEP-neutralino', 'LEP-slepton', 'LEP-sneutrino', 'LEP-squark','neutralino-lsp'
            ]}
