def get():
    return d
d= {
    'colz_chi2':{
        'colz':True,
        'colorbar':True,
        'vmin':30,
        'vmax':45,
    },
    'colz_chi2_20':{
        'colz':True,
        'colorbar':True,
        'vmin':20,
        'vmax':30,
    },
    'colz_chi2_20_mask':{
        'colz':True,
        'colorbar':True,
        'vmin':20,
        'vmax':30,
        'mask_dchi2_gt':25,
    },
    'colz_chi2_20_45_mask':{
        'colz':True,
        'colorbar':True,
        'vmin':20,
        'vmax':45,
        'mask_dchi2_gt':25,
    },
    'colz_dchi2':{
        'colz':True,
        'colorbar':True,
        'vmin':0,
        'vmax':9,
        'dchi2_mode':True,
        'bar_label':r'$\Delta\chi^2$'
    },
    'colz_zaxis':{
        'colz':True,
        'colorbar':True,
        'vmin':'zaxis_vmin',
        'vmax':'zaxis_vmax',
        'bar_label':'zaxis_texname',
    },
    'colz_EWPO_zaxis':{
        'colz':True,
        'colorbar':True,
        'cmap':'my_cmap',
        'vmin':'zaxis_vmin',
        'vmax':'zaxis_vmax',
        'bar_label':'zaxis_texname',
        'mask_dchi2_gt':5.99,
        'chi2_minimum':35.0685330746,
        'zaxis_colorbar_ticks':True,
        'zaxis_colorbar_ticklabels':True,
    },
    'solid_contours':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'g',
    },
    'stau_contours':{
        'contours': True,    
        'levels':[250,500,1500],
        'contour_colors':['m','g','k'],
        'contour_linestyle':'solid',
        'mask_dchi2_gt':5.99,
        'min_segment_length':10,
        'chi2_minimum':35.0685330746,
    },
    'stau_contours_dashed':{
        'contours': True,    
        'levels':[250,500,1500],
        'contour_colors':['m','g','k'],
        'contour_linestyle':'dashed',
        'mask_dchi2_gt':15,
        'mask_dchi2_st':5.99,
        'min_segment_length':10,
        'chi2_minimum':35.0685330746,
    },
    'solid_contours_gold_star':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'gold',
        'chi2_minimum_edge_color':'gold',
    },
    'dashed_contours':{
        'contours': True,    
        'levels': [5.99, 2.30],
        'contour_colors': ['b','r'],
        'dchi2_mode': True,
        'min_segment_length': 10,
        'contour_linestyle':'dashed',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'none',
        'chi2_minimum_edge_color':'g',
     },
    'mc9_neg_mu_cmssm_solid_contours':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':0,
        'contour_linestyle':'solid',
        'chi2_minimum' : 35.0685330746,
        'plot_rowid': 57780685,
        'rowid_fill_color':'gold',
        'rowid_edge_color':'gold',
    },
    'mc9_cmssm_solid_contours':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':0,
        'contour_linestyle':'solid',
        'chi2_minimum' : 35.0685330746,
    },
    '1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
     #   'chi2_minimum' : 35.65,
     #   'chi2_minimum' : 35.0685330746,
        'color': 'b',
        'linestyle':'solid',
    },
    'cmssm_mc9lux_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 35.0685330746,
        'color': 'b',
        'linestyle':'solid',
    },
    'cmssm_mc9lux_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 35.0685330746,
        'color':'b',
        'linestyle':'dotted',
    },
    'nuhm1_mc9lux_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.743709,
        'color': 'b',
        'linestyle':'solid',
    },
    'nuhm1_mc9lux_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.743709,
        'color':'b',
        'linestyle':'dotted',
    },
    'nuhm1_mc8new_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 30.541221,
        'color': 'b',
        'linestyle':'solid',
    },
    'nuhm1_mc8new_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 30.541221,
        'color':'b',
        'linestyle':'dotted',
    },
    'cmssm_mc8new_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.636889,
        'color': 'b',
        'linestyle':'solid',
    },
    'cmssm_mc8new_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.636889,
        'color': 'b',
        'linestyle':'dotted',
    },
    '1d_dchi2_dashed':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'color':'b',
        'linestyle':'dashed',
    },
    '1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'color':'b',
        'linestyle':'dashed',
    },
}
