def get():
    return d
d= {
    'colz_chi2':{
        'colz':True,
        'colorbar':True,
        'vmin':30,
        'vmax':45,
    },
    'colz_chi2_mask':{
        'colz':True,
        'colorbar':True,
        'vmin':30,
        'vmax':45,
        'mask_dchi2_gt': 5.99,
        'bar_label':r'$\chi^2$',
    },
    'colz_chi2_20':{
        'colz':True,
        'colorbar':True,
        'vmin':20,
        'vmax':30,
    },
    'colz_chi2_20_mask':{
        'colz':True,
        'colorbar':True,
        'vmin':20,
        'vmax':30,
        'mask_dchi2_gt': 5.99,
        'bar_label':r'$\chi^2$',
    },
    'colz_chi2_20_45_mask':{
        'colz':True,
        'colorbar':True,
        'vmin':20,
        'vmax':45,
        'mask_dchi2_gt':25,
    },
    'colz_dchi2':{
        'colz':True,
        'colorbar':True,
        'vmin':0,
        'vmax':9,
        'dchi2_mode':True,
        'bar_label':r'$\Delta\chi^2$'
    },
    'colz_zaxis':{
        'colz':True,
        'colorbar':True,
        'vmin':'zaxis_vmin',
        'vmax':'zaxis_vmax',
        'bar_label':'zaxis_texname',
    },
    'colz_zaxis_transparent_red':{
        'colz':True,
        'mask_dchi2_gt': 5.99,
#        'colorbar':True,
        'vmin': 0.1,
        'vmax': 0.11,
        'bar_label':'zaxis_texname',
        'cmap':{'transparent':{'color':'red'}},
    },
    'arrow_constraint': {
        'constraint_arrow_options': {
            'level': 5.99,
            'nth_level':0,
            },
        },
    'arrow_constraint_last': {
        'constraint_arrow_options': {
            'level': 5.99,
            'nth_level':-1,
            },
        },
    'colz_zaxis_transparent_green':{
        'colz':True,
        'mask_dchi2_gt': 5.99,
#        'colorbar':True,
        'vmin': 0.1,
        'vmax': 0.11,
        'bar_label':'zaxis_texname',
        'cmap':{'transparent':{'color':'green'}},
    },
    'colz_zaxis_transparent_magenta':{
        'colz':True,
        'mask_dchi2_gt': 5.99,
#        'colorbar':True,
        'vmin': 0.3,
        'vmax': 0.31,
        'bar_label':'zaxis_texname',
        'cmap':{'transparent':{'color':'magenta'}},
    },
    'colz_zaxis_transparent_black':{
        'colz':True,
        'mask_dchi2_gt': 5.99,
#        'colorbar':True,
        'vmin': 0.2,
        'vmax': 0.21,
        'bar_label':'zaxis_texname',
        'cmap':{'transparent':{'color':'black'}},
    },
    'colz_zaxis_transparent_cyan':{
        'colz':True,
        'mask_dchi2_gt': 5.99,
#        'colorbar':True,
        'vmin': 0.5,
        'vmax': 0.51,
        'bar_label':'zaxis_texname',
        'cmap':{'transparent':{'color':'cyan'}},
    },
    'colz_zaxis_transparent_yellow':{
        'colz':True,
        'mask_dchi2_gt': 5.99,
#        'colorbar':True,
        'vmin': 0.1,
        'vmax': 0.11,
        'bar_label':'zaxis_texname',
        'cmap':{'transparent':{'color':'yellow'}},
    },
    'colz_zaxis_transparent_blue':{
        'colz':True,
        'mask_dchi2_gt': 5.99,
#        'colorbar':True,
        'vmin':0.2,
        'vmax':0.21,
        'bar_label':'zaxis_texname',
        'cmap':{'transparent':{'color':'b'}},
    },
    'empty_star':{
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'none',
        'chi2_minimum_edge_color':'g',
     },
    'colz_zaxis_RdBu':{
        'colz':True,
        'colorbar':True,
        'cmap':'RdBu',
        'vmin':'zaxis_vmin',
        'vmax':'zaxis_vmax',
        'bar_label':'zaxis_texname',
    },
    'colz_zaxis_binning':{
        'colz':True,
        'colorbar':True,
        'vmin':'zaxis_binning_low',
        'vmax':'zaxis_binning_high',
        'bar_label':'zaxis_texname',
    },
    'colz_EWPO_zaxis':{
        'colz':True,
        'colorbar':True,
        'cmap':'my_cmap',
        'vmin':'zaxis_vmin',
        'vmax':'zaxis_vmax',
        'bar_label':'zaxis_texname',
        'mask_dchi2_gt':5.99,
        'chi2_minimum':35.0685330746,
        'zaxis_colorbar_ticks':True,
        'zaxis_colorbar_ticklabels':True,
    },
    'snowmass':{
        'snowmass': True,
    },
    'solid_contours':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':30,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'g',
    },
    'solid_contours_snowmass':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'g',
        'snowmass': True,
    },
    'solid_contours_alpha_075':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'contour_alphas':[0.75,0.75],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_alpha': 0.75,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'none',
    },
    'solid_contours_alpha_005':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'contour_alphas':[0.05,0.05],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_alpha': 0.05,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'none',
    },
    'solid_contours_alpha_05':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'contour_alphas':[0.5,0.5],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_alpha': 0.5,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'none',
    },
    'solid_contours_alpha_025':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'contour_alphas':[0.25,0.25],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_alpha': 0.25,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'none',
    },
    'solid_contours_white':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['w','r'],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'g',
        'chi2_minimum_edge_color':'g',
    },
    'solid_constraint_2d_contours':{
        'contours': True,    
        'levels':[5.99],
        'contour_colors':['b','r'],
        'contour_linestyle':'solid',
    },
    'solid_constraint_1d_contours':{
        'contours': True,    
        'levels':[3.84],
        'contour_colors':['b','r'],
        'contour_linestyle':'solid',
    },
    'dashed_constraint_2d_contours':{
        'contours': True,    
        'levels':[5.99],
        'contour_colors':['b','r'],
        'contour_linestyle':'dashed',
    },
    'dashed_constraint_1d_contours':{
        'contours': True,    
        'levels':[3.84],
        'contour_colors':['b','r'],
        'contour_linestyle':'dashed',
    },
    'stau_contours':{
        'contours': True,    
        'levels':[250,500,1500],
        'contour_colors':['m','g','k'],
        'contour_linestyle':'solid',
        'mask_dchi2_gt':5.99,
        'min_segment_length':10,
        'chi2_minimum':35.0685330746,
    },
    'stau_contours_dashed':{
        'contours': True,    
        'levels':[250,500,1500],
        'contour_colors':['m','g','k'],
        'contour_linestyle':'dashed',
        'mask_dchi2_gt':15,
        'mask_dchi2_st':5.99,
        'min_segment_length':10,
        'chi2_minimum':35.0685330746,
    },
    'solid_contours_gold_star':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':10,
        'contour_linestyle':'solid',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'gold',
        'chi2_minimum_edge_color':'gold',
    },
    'mc10_dashed_contours':{
        'contours': True,    
        'levels': [5.99],
        'contour_colors': ['b'],
        'dchi2_mode': True,
        'min_segment_length': 10,
        'contour_linestyle':'dashed',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'lightgreen',
        'chi2_minimum_edge_color':'g',
     },
    'mc10_dotted_contours':{
        'contours': True,    
        'levels': [5.99],
        'contour_colors': ['b'],
        'dchi2_mode': True,
        'min_segment_length': 10,
        'contour_linestyle':'dotted',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'none',
        'chi2_minimum_edge_color':'g',
     },
    'mc10_2_dashed_contours':{
        'contours': True,    
        'levels': [5.99, 2.30],
        'contour_alphas':[0.5,0.5],
        'contour_linewidths':[1.3, 1.3],
        'contour_colors': ['b','r'],
        'dchi2_mode': True,
        'min_segment_length': 20,
        'contour_linestyle':'dashed',
        'plot_chi2_minimum': True,
        'chi2_minimum_alpha': 0.5,
        'chi2_minimum_fill_color':'lightgreen',
        'chi2_minimum_edge_color':'g',
     },
    'mc10_2_dotted_contours':{
        'contours': True,    
        'levels': [5.99, 2.30],
        'contour_alphas':[0.5,0.5],
        'contour_linewidths':[1.0, 1.0],
        'contour_colors': ['b','r'],
        'dchi2_mode': True,
        'min_segment_length': 20,
        'contour_linestyle':'dotted',
        'plot_chi2_minimum': True,
        'chi2_minimum_alpha': 0.5,
        'chi2_minimum_fill_color':'none',
        'chi2_minimum_edge_color':'g',
     },
    'dashed_contours':{
        'contours': True,    
        'levels': [5.99, 2.30],
        'contour_colors': ['b','r'],
        'dchi2_mode': True,
        'min_segment_length': 10,
        'contour_linestyle':'dashed',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'none',
        'chi2_minimum_edge_color':'g',
     },
    'dotted_contours':{
        'contours': True,    
        'levels': [5.99, 2.30],
        'contour_colors': ['b','r'],
        'dchi2_mode': True,
        'min_segment_length': 10,
        'contour_linestyle':'dotted',
        'plot_chi2_minimum': True,
        'chi2_minimum_fill_color':'none',
        'chi2_minimum_edge_color':'g',
     },
    'mc9_neg_mu_cmssm_solid_contours':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':0,
        'contour_linestyle':'solid',
        'chi2_minimum' : 35.0685330746,
        'plot_rowid': 57780685,
        'rowid_fill_color':'gold',
        'rowid_edge_color':'gold',
    },
    'mc9_cmssm_solid_contours':{
        'contours': True,    
        'levels':[5.99, 2.30],
        'contour_colors':['b','r'],
        'dchi2_mode': True,
        'min_segment_length':0,
        'contour_linestyle':'solid',
        'chi2_minimum' : 35.0685330746,
    },
    '1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
     #   'chi2_minimum' : 35.65,
     #   'chi2_minimum' : 35.0685330746,
        'color': 'b',
        'linestyle':'solid',
    },
    '1d_dchi2_black':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
     #   'chi2_minimum' : 35.65,
     #   'chi2_minimum' : 35.0685330746,
        'color': 'k',
        'linestyle':'solid',
    },
    'cmssm_mc9lux_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 35.0685330746,
        'color': 'b',
        'linestyle':'solid',
    },
    'cmssm_mc9lux_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 35.0685330746,
        'color':'b',
        'linestyle':'dotted',
    },
    'nuhm1_mc9lux_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.743709,
        'color': 'b',
        'linestyle':'solid',
    },
    'nuhm1_mc9lux_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.743709,
        'color':'b',
        'linestyle':'dotted',
    },
    'nuhm1_mc8new_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 30.541221,
        'color': 'b',
        'linestyle':'solid',
    },
    'nuhm1_mc8new_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 30.541221,
        'color':'b',
        'linestyle':'dotted',
    },
    'cmssm_mc8new_1d_dchi2':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.636889,
        'color': 'b',
        'linestyle':'solid',
    },
    'cmssm_mc8new_1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'chi2_minimum' : 32.636889,
        'color': 'b',
        'linestyle':'dotted',
    },
    '1d_dchi2_dashed':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'color':'b',
        'linestyle':'dashed',
    },
    '1d_dchi2_dotted':{
        'dchi2_mode': True,
        'ymin':0,    
        'ymax':9,   
        'ylabel':r'$\Delta\chi^2$',
        'color':'b',
        'linestyle':'dotted',
    },
    '1d_chi2':{
        'ymin':20,    
        'ymax':45,   
        'ylabel':r'$\chi^2$',
        'color':'b',
        'linestyle':'solid',
    },
    '1d_chi2_dashed':{
        'ymin':20,    
        'ymax':45,   
        'ylabel':r'$\chi^2$',
        'color':'b',
        'linestyle':'dashed',
    },
    '1d_chi2_dotted':{
        'ymin':20,    
        'ymax':45,   
        'ylabel':r'$\chi^2$',
        'color':'b',
        'linestyle':'dotted',
    },
    '1d_chi2_black':{
        'ymin':20,    
        'ymax':45,   
        'ylabel':r'$\chi^2$',
        'color':'k',
        'linestyle':'solid',
    },
    '1d_constraint_red':{
        'ylabel':r'$\chi^2$',
        'color':'red',
        'linestyle':'dashed',
        'linewidth': 1.0,
    },
    '1d_constraint_magenta':{
        'ylabel':r'$\chi^2$',
        'color':'magenta',
        'linestyle':'dashed',
        'linewidth': 1.0,
    },
    '1d_constraint_black':{
        'ylabel':r'$\chi^2$',
        'color':'black',
        'linestyle':'dashed',
        'linewidth': 1.0,
    },
}
