{
     'g-2':{
        'value':'g-2',
        'binning':{
            'low':-1.0e-9,
            'high':6.0e-9,
            'nbins': 100,
            'type': 'linear',
            },
        'texname': r'$\Delta \left( \frac{g-2}{2} \right)$',
        },
    'stau_coannihilation_measure':{
        'value':'stau_coannihilation_measure',
        },
    'stop_coannihilation_measure':{
        'value':'stop_coannihilation_measure',
        },
    'neu2_coannihilation_measure':{
        'value':'neu2_coannihilation_measure',
        },
    'char_coannihilation_measure':{
        'value':'char_coannihilation_measure',
        },
    'focus_point_measure':{
        'value': 'focus_point_measure',
        },
    'A_funnel_measure':{
        'value': 'A_funnel_measure',
        },
    'chi2_universal_limits_7TeV':{
        'value':'chi2-universal_limits_7TeV',
        'vmin':0,
        'vmax':4,
        'texname':r'$\chi^2(universal@7TeV)$'
        },
    'chi2_m0_m12_7TeV':{
        'value':'chi2-atlas5_m0_m12',
        'vmin':0,
        'vmax':5.99,
        'texname':r'$\chi^2(atlas@7TeV)$'
        },
    'pmssm-mc9-chi2':{
        'binning':{
            'low':24,
            'high':35,
            'nbins':10000,
            'type':'linear',
            },
        'value':'mc9_no_lhc',
        },
    'cmssm-mc9-chi2':{
        'binning':{
            'low':30,
            'high':45,
            'nbins':2000,
            'type':'linear',
            },
        'value':'mc9',
        },
    'mtop': {
        'binning': {
            'high': 175.2,
            'low': 171.2,
            'nbins': 100,
            'type': 'linear'
            },
        'value': 'mtop'},
    'A': {
        'binning': {
            'high': 5000.0,
            'low': -5000.0,
            'nbins': 100,
            'type': 'linear'
            },
        'value': 'A'},
    'A0': {
        'binning': {
            'high': 5000.0,
            'low': -5000.0,
            'nbins': 100,
            'type': 'linear'
            },
        'value': 'A0',
        'texname': r'$A_0$',
        },
    'A0_nuhm2': {
        'binning': {
            'high': 8000.0,
            'low': -8000.0,
            'nbins': 100,
            'type': 'linear'
            },
        'value': 'A0',
        'xticks': 4000,
        'texname':r'$A_0$',
        },
    'A0_ko_nuhm2': {
        'binning': {
            'high': 8000.0,
            'low': -8000.0,
            'nbins': 100,
            'type': 'linear'
            },
        'value': 'A0_ko',
        'xticks': 4000,
        'texname':r'$A_0$',
        },
    'A0_over_m0': {
        'binning': {
            'high': 5.0,
            'low': -5.0,
            'nbins': 100,
            'type': 'linear'
            },
        'value': 'A0_over_m0'
        },
    'BsmmRatio': {
        'binning': {
            'high': 3.0,
            'low': 0.0,
            'nbins': 100,
            'type': 'linear'
            },
        'vmin':0.5,
        'vmax':1.5,
        'value': 'BsmmRatio',
        'texname':r'$R_{\mu\mu}$',
        },
    'C9': {'binning': {'high': 0.05,
                       'low': -0.05,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'C9'},
    'M1': {'binning': {'high': 2500.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'M1'},
    'M2': {'binning': {'high': 2500.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'M2'},
    'M3': {'binning': {'high': 2500.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'M3'},
    'pm-M1': {'binning': {'high': 1000.0,
                       'low': -1000.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'M1'},
    'pm-M2': {'binning': {'high': 4000.0,
                       'low': -1000.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'M2'},
    'pm-M3': {'binning': {'high': 4000.0,
                       'low': -4000,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'M3'},
    'MA': {'binning': {'high': 4000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'MA',
           'xticks': 1000,
           'texname':r'$M_A$[GeV]'},
    'MA_6K': {'binning': {'high': 6000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'MA',
           'xticks': 1000,
           'texname':r'$M_A$[GeV]'},
    'MA_2500': {'binning': {'high': 2500.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'MA',
           'texname':r'$M_A$[GeV]'},
    'chi2': {'binning': {'high': 300.0,
                         'low': 30.0,
                         'nbins': 500,
                         'type': 'linear'},
             'value': 'chi2'},
    'chi2_g-2': {'value': 'g-2'},
    'chi2_jad': {'value': 'universal_limits'},
    'chi2_m3g_only': {'value': 'm3g_universal_limits'},
    'chi2_mg_only': {'value': 'mg_universal_limits'},
    'chi2_mh': {'value': 'Mh125'},
    'chi2Oh2': {
            'value': 'chi2Oh2',
            },
    'in_ma': {
            'binning': {
                'high': 4000.0,
                'low': 0.0,
                'nbins': 100,
                'type': 'linear'
                },
            'value': 'in_ma'},
    'in_mu': {'binning': {'high': 5000.0,
                          'low': -5000.0,
                          'nbins': 100,
                          'type': 'linear'},
              'value': 'in_mu'},
    'logmneu1': {'binning': {'high': 4000.0,
                             'low': 10.0,
                             'nbins': 100,
                             'type': 'log'},
                 'value': 'mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
                 },
    'logabsmneu1': {'binning': {'high': 4000.0,
                             'low': 10.0,
                             'nbins': 100,
                             'type': 'log'},
                 'value': 'abs_mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
                 },
    'logabsmneu1_10K': {'binning': {'high': 10000.0,
                             'low': 10.0,
                             'nbins': 100,
                             'type': 'log'},
                 'value': 'abs_mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
                 },
    'logabsmneu1_SNOW': {'binning': {'high': 10000.0,
                             'low': 0.5,
                             'nbins': 100,
                             'type': 'log'},
                 'value': 'abs_mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
                 },
    'logssicm2': {'binning': {'high': 1e-40,
                              'low': 1e-48,
                              'nbins': 100,
                              'type': 'log'},
                  'value': 'ssicm2',
                  'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                  },
    'logssikocm2_SNOW': {'binning': {'high': 1e-39,
                              'low': 1e-50,
                              'nbins': 100,
                              'type': 'log'},
                  'value': 'ssikocm2',
                  'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                  },
    'logssikocm2_MC10': {'binning': {'high': 1e-41,
                              'low': 1e-50,
                              'nbins': 100,
                              'type': 'log'},
                  'value': 'ssikocm2',
                  'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                  },
    'logssipb': {'binning': {'high': 1e-5,
                              'low': 1e-26,
                              'nbins': 100,
                              'type': 'log'},
                  'value': 'ssi',
                  'texname': r'$\sigma^{SI}_p$[pb]',
                  },
    'logssicm2_t': {'binning': {'high': 1e-41,
                              'low': 1e-62,
                              'nbins': 100,
                              'type': 'log'},
                  'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                  'value': 'ssikocm2',
                  },
    'logssipb_oh2': {'binning': {'high': 1e-4,
                              'low': 1e-24,
                              'nbins': 100,
                              'type': 'log'},
                  'value': 'ssi',
                  'texname': r'$\sigma^{SI}_p$[pb]',
                  },
    'logssdpb': {'binning': {'high': 1,
                              'low': 1e-20,
                              'nbins': 100,
                              'type': 'log'},
                  'value': 'ssd',
                  'texname': r'$\sigma^{SD}_p$[pb]',
                  },
    'logssikocm2': {'binning': {'high': 1e-40,
                                'low': 1e-48,
                                'nbins': 100,
                                'type': 'log'},
                    'value': 'ssikocm2',
                    'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                    },
    'logssikocm2_50': {'binning': {'high': 1e-40,
                                'low': 1e-50,
                                'nbins': 100,
                                'type': 'log'},
                    'value': 'ssikocm2',
                    'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                    },
    'logssikocm2_61': {'binning': {'high': 1e-40,
                                'low': 1e-61,
                                'nbins': 100,
                                'type': 'log'},
                    'value': 'ssikocm2',
                    'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                    },
    'logssikocm2_55': {'binning': {'high': 1e-40,
                                'low': 1e-55,
                                'nbins': 100,
                                'type': 'log'},
                    'value': 'ssikocm2',
                    'texname': r'$\sigma^{SI}_p$[cm$^2$]',
                    },
    'Dssicm2': {
            'value': 'Dssikocm2'
            },
    'Dssi': {
            'value': 'Dssi'
            },
    'm0': {'binning': {'high': 4000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'm0',
           'xticks': 1000,
           'texname':r'$m_0$[GeV]'},
    'm0_nuhm2': {'binning': {'high': 4000.0,
                       'low': -1000.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'm0',
           'xticks': 1000,
           'texname':r'$m_0$[GeV]'},
    'mstau1-mneu1': {'binning': {'high': 30.0,
                       'low': -5.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mstau1-mneu1'},
    'mchar1-mneu1': {'binning': {'high': 30.0,
                       'low': -5.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mchar1-mneu1'},
    'MA-2mneu1': {'binning': {'high': 30.0,
                       'low': -5.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'MA-2mneu1'},
    'nuhm1m0': {'binning': {'high': 4500.0,
                       'low': -500.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'm0'},
    'm0_6K': {'binning': {'high': 6000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'm0',
           'texname':r'$m_0$[GeV]'},
    'm0_7K': {'binning': {'high': 7000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'm0',
           },
    'm12': {'binning': {'high': 4000.0,
                        'low': 0.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'm12',
            'texname':r'$m_{1/2}$[GeV]'},
    'm12g': {'binning': {'high': 4000.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'm12g'},
    'm12g_2K': {'binning': {'high': 2000.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
            'texname':'m12g',
             'value': 'm12g'},
    'm3g': {'binning': {'high': 4000.0,
                        'low': 0.0,
                        'nbins': 100,
                        'type': 'linear'},

            'value': 'm3g'},
    'm3g_2K': {'binning': {'high': 2000.0,
                        'low': 0.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'm3g',
            'texname':'m3g',
            },
    'abs_mchar1': {'binning': {'high':4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'abs_mchar1',
               'texname': r'$m_{\tilde{\chi}^{\pm}_1}$[GeV]',
               },
    'mchar1': {'binning': {'high':4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mchar1'},
    'pm-mchar1': {'binning': {'high':4000.0,
                           'low': -4000.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mchar1'},
    'mchar1_2K': {'binning': {'high':2000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
                 'texname': r'$m_{\tilde{\chi}^{\pm}_1}$[GeV]',
               'value': 'mchar1'},
    'abs_mchar1_2K': {'binning': {'high':2000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
                 'texname': r'$m_{\tilde{\chi}^{\pm}_1}$[GeV]',
               'value': 'abs_mchar1'},
    'mchar1_2_5K': {'binning': {'high':2500.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'texname':r'$m_{\tilde{\chi}^{\pm}_1}$[GeV]',
               'value': 'mchar1'},
    'mchar1_4K': {'binning': {'high':4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'texname':r'$m_{\tilde{\chi}^{\pm}_1}$[GeV]',
               'value': 'mchar1'},
    'mchar1_5K': {'binning': {'high':5000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'texname':r'$m_{\tilde{\chi}^{\pm}_1}$[GeV]',
               'value': 'mchar1'},
    'mchar1_6K': {'binning': {'high':6000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'texname':r'$m_{\tilde{\chi}^{\pm}_1}$[GeV]',
               'value': 'mchar1'},
    'pm-mg': {'binning': {'high': 4000.0,
                       'low': -4000.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mg',
           'xticks': 1000,
           'texname':r'$m_{\tilde{g}}$[GeV]'},
    'abs_mg_2K': {
            'binning': {'high': 2000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'abs_mg',
           'texname':r'$m_{\tilde{g}}$[GeV]'},
    'abs_mg_4K': {
            'binning': {'high': 4000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'abs_mg',
           'texname':r'$m_{\tilde{g}}$[GeV]'},
    'abs_mg': {
            'binning': {'high': 4000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'abs_mg',
           'texname':r'$m_{\tilde{g}}$[GeV]'},
    'mg': {'binning': {'high': 4000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mg',
           'xticks': 1000,
           'texname':r'$m_{\tilde{g}}$[GeV]'},
    'mg_cms_twiki': {
            'binning': {'high': 1500.0,
                       'low': 560.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mg',
           'xticks': 100,
           'texname':r'$m_{\tilde{g}}$[GeV]'},
    'mg_140131': {
            'binning': {'high': 4100.0,
                       'low': 1500.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mg',
           'xticks': 1000,
           'texname':r'$m_{\tilde{g}}$[GeV]'},
    'mg_6K': {'binning': {'high': 6000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mg',
           'texname':r'$m_{\tilde{g}}$[GeV]'
           },
    'mg_5K': {'binning': {'high': 5000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mg',
           'texname':r'$m_{\tilde{g}}$[GeV]'
           },
    'mg_2K': {'binning': {'high': 2000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mg',
           'xticks': 250,
           'texname':r'$m_{\tilde{g}}$[GeV]'
           },
    'mh': {'binning': {'high': 130.0,
                       'low': 105.0,
                       'nbins': 100,    
                       'type': 'linear'},
           'value': 'mh',
           'texname':'$M_h$[GeV]'},
    'mh_zoom': {'binning': {'high': 130.0,
                       'low': 120.0,
                       'nbins': 100,    
                       'type': 'linear'},
           'value': 'mh',
           'texname':'$M_h$[GeV]'},
    'Dmh': {'binning': {'high': 40.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'Dmh'},
    'Dmh_20': {'binning': {'high': 20.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'Dmh'},
    'Dmh_10': {'binning': {'high': 10.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'Dmh'},
    'Dmh_5': {'binning': {'high': 5.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'Dmh'},
    'fh-ss': {'binning': {'high': 40,
                       'low': -40,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'fh-ss'},
    'fh-ss_20': {'binning': {'high': 20,
                       'low': -20,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'fh-ss'},
    'fh-ss_10': {'binning': {'high': 10,
                       'low': -10,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'fh-ss'},
    'fh-ss_5': {'binning': {'high': 5,
                       'low': -5,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'fh-ss'},
    'mh2': {'binning': {'high': 46000000.0,
                        'low': -46000000.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'mh2'},
    'mhu2': {'binning': {'high': 50000000.0,
                        'low': -50000000.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'mhu2',
            'texname':r'$m_{H_u}^2$',
            },
    'mhd2': {'binning': {'high': 50000000.0,
                        'low': -50000000.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'mhd2',
            'texname':r'$m_{H_d}^2$',
            },
    'mhu2_1e8': {'binning': {'high': 0.0,
                        'low': -1.0e8,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'mhu2',
            'texname':r'$m_{H_u}^2$',
            },
    'mhd2_1e8': {'binning': {'high': 0.0,
                        'low': -1.0e8,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'mhd2',
            'texname':r'$m_{H_d}^2$',
            },
    'mhu2_big': {'binning': {'high': 75000000.0,
                        'low': -75000000.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'mhu2',
            'texname':r'$m_{H_u}^2$',
            },
    'mhd2_big': {'binning': {'high': 75000000.0,
                        'low': -75000000.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'mhd2',
            'texname':r'$m_{H_d}^2$',
            },
    'mh2_m0^2_Ratio': {'binning': {'high': 10.0,
                                   'low': -10.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'value': 'mh2_m0^2_Ratio'},
    'mh_over_m0': {'binning': {'high': 10.0,
                               'low': -10.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'value': 'mh_over_m0'},
    'mneu1': {'binning': {'high':4000.0,
                          'low': 0.0,
                          'nbins': 100,
                          'type': 'linear'},
              'value': 'mneu1',
              'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
              },
    'mneu1_cms_twiki': {
            'binning': {'high':950.0,
                          'low': 0.0,
                          'nbins': 100,
                          'type': 'linear'},
              'value': 'mneu1',
              'yticks':100,
              'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
              },
    'pm-mneu1': {'binning': {'high':1000.0,
                          'low': -1000.0,
                          'nbins': 100,
                          'type': 'linear'},
              'value': 'mneu1',
              'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
              },
    'mneu1_50gev': {'binning': {'high':50.0,
                          'low': 0.0,
                          'nbins': 100,
                          'type': 'linear'},
              'value': 'mneu1',
              'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
              },
    'mneu1_900': {'binning': {'high': 900.0,
                              'low': 0.0,
                              'nbins': 100,
                              'type': 'linear'},
                  'value': 'mneu1_900'},
    'msbot1': {'binning': {'high': 4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'msbot1'},
    'msbot2': {'binning': {'high': 4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'msbot2'},
    'msl': {'binning': {'high': 4000.0,
                        'low': 0.0,
                        'nbins': 100,
                        'type': 'linear'},
            'value': 'msl'},
    'msq12': {'binning': {'high': 4000.0,
                          'low': 0.0,
                          'nbins': 100,
                          'type': 'linear'},
              'value': 'msq12'},
    'msq3': {'binning': {'high': 4000.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'msq3'},
    'msqr': {'binning': {'high': 6000.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'msqr',
             'texname': r'$m_{\tilde{q}_R}$[GeV]'
             },
    'msqr_2K': {'binning': {'high': 2000.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'msqr',
             'texname': r'$m_{\tilde{q}_R}$[GeV]'
             },
    'msqr_4K': {'binning': {'high': 4000.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'msqr',
             'texname': r'$m_{\tilde{q}_R}$[GeV]'
             },
    'msqr_ICHEP_2K': {'binning': {'high': 2000.0,
                         'low': 200.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'msqr',
             'texname': r'$m_{\tilde{q}_R}$[GeV]'
             },
    'msqr_140131': {
            'binning': {'high': 4100.0,
                         'low': 1900.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'msqr',
             'texname': r'$m_{\tilde{q}_R}$[GeV]'
             },
    'msqr_8K': {'binning': {'high': 8000.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'msqr',
             'texname': r'$m_{\tilde{q}_R}$[GeV]'
             },
    'mstau1': {'binning': {'high':4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstau1',
               'vmin':0,
               'vmax':2000,
               'xticks': 1000,
               'texname':r'$m_{\tilde{\tau}_1}$[GeV]',
               },
    'mstau1_6K': {'binning': {'high': 6000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstau1',
               'texname':r'$m_{\tilde{\tau}_1}$[GeV]',
               },
    'mstau1_5K': {'binning': {'high': 5000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstau1',
               'texname':r'$m_{\tilde{\tau}_1}$[GeV]',
               },
    'mstau1_2K': {'binning': {'high': 2000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstau1',
               'texname':r'$m_{\tilde{\tau}_1}$[GeV]',
               },
    'mstop1': {'binning': {'high': 4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
               'xticks': 1000,
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop1_ICHEP_800': {'binning': {'high': 800.0,
                           'low': 80.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
               'xticks': 100,
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop1_ICHEP_1200': {'binning': {'high':1200.0,
                           'low':100.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
               'xticks': 100,
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop1_ICHEP_1500': {'binning': {'high': 1500.0,
                           'low': 80.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
                'xticks': 200,
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop1_ICHEP_2000': {'binning': {'high': 2000.0,
                           'low': 80.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
       #        'xticks': 200,
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop1_2K': {'binning': {'high': 2000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop1_5K': {'binning': {'high': 5000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop1_6K': {'binning': {'high': 6000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mstop2': {'binning': {'high': 4000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'xticks': 1000,
               'texname':r'$m_{\tilde{t}_2}$[GeV]',
               'value': 'mstop2'},
    'mstop2_2K': {'binning': {'high': 2000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'xticks': 1000,
               'value': 'mstop2'},
    'mstop2-mstop1': {'binning': {'high': 1000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'value': 'mstop2-mstop1'},
    'mstop1_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstop1',
               'texname':r'$m_{\tilde{t}_1}$[GeV]'
               },
    'mselL_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mselL',
               },
    'msmuL_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'msmuL',
               },
    'abs_mneu2_500': {'binning': {'high': 500.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'abs_mneu2',
                 'texname': r'$m_{\tilde{\chi}^0_2}$[GeV]',
               },
    'abs_mneu2_2K': {'binning': {'high': 2000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'abs_mneu2',
                 'texname': r'$m_{\tilde{\chi}^0_2}$[GeV]',
               },
    'mstau1_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mstau1',
               },
    'mneu1_500': {'binning': {'high': 500.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
               },
    'mneu1_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
               },
    'mneu1_2K': {'binning': {'high': 2000.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
               },
    'mneu1_1250': {'binning': {'high': 1250.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
               },
    'abs_mneu1_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'abs_mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
               },
    'abs_mneu1_500': {'binning': {'high': 500.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'abs_mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
               },
    'abs_mneu1_350': {'binning': {'high': 350.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'abs_mneu1',
                 'texname': r'$m_{\tilde{\chi}^0_1}$[GeV]',
               },
    'mneu2_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mneu2',
               },
    'mchar1_750': {'binning': {'high': 750.0,
                           'low': 0.0,
                           'nbins': 100,
                           'type': 'linear'},
               'value': 'mchar1',
               },
    'mu': {'binning': {'high': 3000.0,
                       'low': 0.0,
                       'nbins': 100,
                       'type': 'linear'},
           'value': 'mu',
           'texname':r'$\mu$'},
    'logoh2': {
            'binning': {
                'low': 1e-6, 
                'high': 1, 
                'nbins': 100, 
                'type': 'log',
                },
            'value': 'oh2'
            },
    'oh2': {
            'binning': {
                'low': 0.0, 
                'high': 0.3, 
                'nbins': 100, 
                'type': 'linear',
                },
            'value': 'oh2'
            },
    'ssmh': {'binning': {'high': 130.0,
                         'low': 105.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'ssmh'},
    'tanb': {'binning': {'high': 60.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'tanb',
             'texname': r'$\tan\beta$'},
    'tanb40': {'binning': {'high': 40.0,
                         'low': 0.0,
                         'nbins': 100,
                         'type': 'linear'},
             'value': 'tanb',
             'texname':r'$\tan\beta$',
             },
    'Delta_alpha_had':{
            'value':'Delta_alpha_had',
           },
    'mz':{
            'value':'mz',
            },
    'mt':{
            'value':'mtop',
            },
    'Xt' : {
            'binning':{
                'low':-5000,
                'high':5000,
                'nbins':100,
                'type':'linear',
                },
            'value':'Xt',
            'texname':r'$X_t$',
                    },
        }
