def get():
    return{
            'A': {
                'binning': {
                    'high': 5000.0,
                    'low': -5000.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'vars_lookup': 'A'},
            'A0': {
                'binning': {
                    'high': 5000.0,
                    'low': -5000.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'vars_lookup': 'A0'
                },
            'A0_over_m0': {
                'binning': {
                    'high': 5.0,
                    'low': -5.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'vars_function': 'A0_over_m0'
                },
            'BsmmRatio': {
                'binning': {
                    'high': 3.0,
                    'low': 0.0,
                    'nbins': 100,
                    'type': 'linear'
                    },
                'vars_function': 'BsmmRatio'
                },
            'C9': {'binning': {'high': 0.05,
                               'low': -0.05,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_function': 'C9'},
            'M1': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'M1'},
            'M2': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'M2'},
            'M3': {'binning': {'high': 2500.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'M3'},
            'MA': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'MA'},
            'chi2': {'binning': {'high': 300.0,
                                 'low': 30.0,
                                 'nbins': 500,
                                 'type': 'linear'},
                     'vars_lookup': 'chi2'},
            'chi2_g-2': {'gauss_constraint': 'g-2'},
            'chi2_jad': {'contour_constraint': 'universal_limits'},
            'chi2_m3g_only': {'contour_constraint': 'm3g_universal_limits'},
            'chi2_mg_only': {'contour_constraint': 'mg_universal_limits'},
            'chi2_mh': {'gauss_constraint': 'Mh125'},
            'chi2_oh2': {'gauss_constraint': 'Oh2'},
            'in_ma': {'binning': {'high': 4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'vars_lookup': 'in_ma'},
            'in_mu': {'binning': {'high': 5000.0,
                                  'low': -5000.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'vars_lookup': 'in_mu'},
            'jadmg': {'binning': {'high': 1600.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'vars_lookup': 'jadmg'},
            'jadmgmneu1': {'binning': {'high': 1600.0,
                                       'low': 0.0,
                                       'nbins': 100,
                                       'type': 'linear'},
                           'vars_lookup': 'jadmgmneu1'},
            'jadmsq3': {'binning': {'high': 900.0,
                                    'low': 0.0,
                                    'nbins': 100,
                                    'type': 'linear'},
                        'vars_lookup': 'jadmsq3'},
            'jadmsq3mneu1': {'binning': {'high': 900.0,
                                         'low': 0.0,
                                         'nbins': 100,
                                         'type': 'linear'},
                             'vars_lookup': 'jadmsq3mneu1'},
            'logmneu1': {'binning': {'high': 1000.0,
                                     'low': 10.0,
                                     'nbins': 100,
                                     'type': 'log'},
                         'vars_lookup': 'logmneu1'},
            'logssicm2': {'binning': {'high': 1e-40,
                                      'low': 1e-48,
                                      'nbins': 100,
                                      'type': 'log'},
                          'vars_function': 'logssicm2'},
            'logssikocm2': {'binning': {'high': 1e-40,
                                        'low': 1e-48,
                                        'nbins': 100,
                                        'type': 'log'},
                            'vars_function': 'logssikocm2'},
            'm0': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'm0'},
            'm12': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'vars_lookup': 'm12'},
            'm12g': {'binning': {'high': 4000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'vars_function': 'm12g'},
            'm3g': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'vars_function': 'm3g'},
            'mchar1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'vars_lookup': 'mchar1'},
            'mg': {'binning': {'high': 4000.0,
                               'low': 0.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'mg'},
            'mh': {'binning': {'high': 130.0,
                               'low': 105.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'mh'},
            'mh2': {'binning': {'high': 12000000.0,
                                'low': -12000000.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'vars_lookup': 'mh2'},
            'mh2_m0^2_Ratio': {'binning': {'high': 10.0,
                                           'low': -10.0,
                                           'nbins': 100,
                                           'type': 'linear'},
                               'vars_function': 'mh2_m0^2_Ratio'},
            'mh_over_m0': {'binning': {'high': 10.0,
                                       'low': -10.0,
                                       'nbins': 100,
                                       'type': 'linear'},
                           'vars_function': 'mh_over_m0'},
            'mneu1': {'binning': {'high': 4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'vars_lookup': 'mneu1'},
            'mneu1_900': {'binning': {'high': 900.0,
                                      'low': 0.0,
                                      'nbins': 100,
                                      'type': 'linear'},
                          'vars_lookup': 'mneu1_900'},
            'msbot1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'vars_lookup': 'msbot1'},
            'msbot2': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'vars_lookup': 'msbot2'},
            'msl': {'binning': {'high': 4000.0,
                                'low': 0.0,
                                'nbins': 100,
                                'type': 'linear'},
                    'vars_lookup': 'msl'},
            'msq12': {'binning': {'high': 4000.0,
                                  'low': 0.0,
                                  'nbins': 100,
                                  'type': 'linear'},
                      'vars_lookup': 'msq12'},
            'msq3': {'binning': {'high': 4000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'vars_lookup': 'msq3'},
            'msqr': {'binning': {'high': 6000.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'vars_function': 'msqr'},
            'mstau1': {'binning': {'high': 6000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'vars_lookup': 'mstau1'},
            'mstop1': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'vars_lookup': 'mstop1'},
            'mstop2': {'binning': {'high': 4000.0,
                                   'low': 0.0,
                                   'nbins': 100,
                                   'type': 'linear'},
                       'vars_lookup': 'mstop2'},
            'mstop2-mstop1': {'binning': {'high': 1000.0,
                                          'low': 0.0,
                                          'nbins': 100,
                                          'type': 'linear'},
                              'vars_function': 'mstop2-mstop1'},
            'mu': {'binning': {'high': 5000.0,
                               'low': -5000.0,
                               'nbins': 100,
                               'type': 'linear'},
                   'vars_lookup': 'mu'},
            'oh2': {'binning': {'high': 0.3, 'low': 0.0, 'nbins': 100, 'type': 'linear'},
                    'vars_lookup': 'oh2'},
            'ssmh': {'binning': {'high': 130.0,
                                 'low': 105.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'vars_lookup': 'ssmh'},
            'tanb': {'binning': {'high': 60.0,
                                 'low': 0.0,
                                 'nbins': 100,
                                 'type': 'linear'},
                     'vars_lookup': 'tanb'}}
