def get_spaces():
    return spaces['cmssm']
#    return spaces['nuhm1']
#    return spaces['pmssm']

spaces={
    'cmssm': [
            {   'axes':['m0','m12'] , 'zaxes':['mh','chi2_mh','mstop1','A0'] },
            { 'axes': 'mh'}
#            {   'axes':'mstop1'  },
#            {   'axes':['m0','mh2_m0^2_Ratio']  },
#            {   'axes':['MA','tanb'],'zaxes':'BsmmRatio'},
#            {   'axes':['m0','tanb'],'zaxes':'BsmmRatio'},
#            {   'axes':['A0','tanb'],'zaxes':'BsmmRatio'},
#            {   'axes':['tanb','m12'],'zaxes':'BsmmRatio'},
#            {   'axes':'mh' }, 
#            {   'axes':'BsmmRatio', 'zaxes':'BsmmRatio' }, 
#            {   'axes':'m0'},
#            {   'axes':'chi2'},
#            {   'axes':['mneu1','mg']},
        ],
    'nuhm1': [
        {   'axes':['m0','m12'],'zaxes':'chi2_jad'},
       ],
   'pmssm':[
#            {'axes':['mneu1','mg'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
            {'axes':['mg','mneu1'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['mg','mneu1']},
#            {'axes':['m3g','mneu1'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['jadmg','jadmgmneu1'],'zaxes':['chi2_jad','chi2_m3g_only']},
#            {'axes':['m3g','jadmsq3mneu1'],'zaxes':['chi2_jad','chi2_m3g_only']},
#            {'axes':['m3g','jadmg'],'zaxes':['chi2_jad','chi2_m3g_only']},
#            {'axes':['jadmg','jadmgmneu1'],'zaxes':['chi2_jad','chi2_mg_only']},
#            {'axes':['m3g','jadmsq3mneu1'],'zaxes':['chi2_jad','chi2_mg_only']},
#            {'axes':['m3g','jadmg'],'zaxes':['chi2_jad','chi2_mg_only']},
#           {'axes':['mneu1','mg']},
#            {'axes':['M1','mg']},
#            {'axes':['M2','mg']},
#            {'axes':['M3','mg']},
#            {'axes':['msq12','tanb']},
#            {'axes':['msq3','tanb']},
           {'axes':['msq3','msq12']},
#            {'axes':['msl' ,'tanb']},
#            {'axes':['msl' ,'msq12']},
#            {'axes':['msl' ,'msq3']},
#            {'axes':['A'   ,'tanb']},
#            {'axes':['A'   ,'msq12']},
#            {'axes':['A'   ,'msq3']},
#            {'axes':['A'   ,'msl']},
#            {'axes':['M1'  ,'tanb']},
#            {'axes':['M1'  ,'msq12']},
#            {'axes':['M1'  ,'msq3']},
#            {'axes':['M1'  ,'msl']},
#            {'axes':['M1'  ,'A']},
#            {'axes':['in_mu','tanb'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_mu','msq12'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_mu','msq3'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_mu','msl'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_mu','A'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_mu','M1'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_mu','M2'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_mu','M3'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['in_ma','tanb']},
#            {'axes':['in_ma','msq12']},
#            {'axes':['in_ma','msq3']},
#            {'axes':['in_ma','msl']},
#            {'axes':['in_ma','A']},
#            {'axes':['in_ma','M1']},
#            {'axes':['in_ma','in_mu'],'zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':['mneu1','mstop1']},
#            {'axes':'mg'},
#            {'axes':['mh','msq3']},
            {'axes':'chi2','zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':'mh'},
#            {'axes':'tanb'},
#            {'axes':'msq12'},
#            {'axes':'msq3'},
#            {'axes':'msl' },
#            {'axes':'A'   },
#            {'axes':'M1'  },
            {'axes':'mg'  },
            {'axes':'mneu1'  },
#            {'axes':'in_mu','zaxes':['chi2_mh','chi2_oh2','chi2_g-2']},
#            {'axes':'in_ma','zaxes':'mh'},
#            {'axes':'mh','zaxes':'chi2_mh'},
#            {'axes':'mh'},
#            {   'axes':'BsmmRatio', 'zaxes':['BsmmRatio','chi2_mh'] }, 
                   ],
    }
